### ISSUE TITLE
A class to fill all the holidays from Brazil

### ISSUE THREAD

**Issue by royopa** [andrejsstepanovs/business-days-calculator#7]
Hi

I created a class CalculatorBrazil that extends \BusinessDays\Calculator and fill all the official Brazil holidays extracted from [Anbima](http://www.anbima.com.br/feriados/feriados.asp).

What do you think about merge this class to this project? Or you prefer that I create a new repository   dependent of \BusinessDays\Calculator?

**Comment by andrejsstepanovs** [comment]
Hi! I never intended to include data into this library. It is intended to be able to make calculations based on given data. Where that data is coming from depends completely on application. That is why even Saturday and Sunday as free week days needs to be set by application. 

Also I don't see how you can hardcode every free day in your class. It will change year by year because not all free days are happening on the same date. Some religious holidays are happening for example second monday of a X month. And there will be more things like that, that you can not predict easily. I advise you to store this info in some data storage and build interface for users (employees or admin) to be able to change it year by year. Or just hardcode it in application. ;)

**Comment by royopa** [comment]
Ok @andrejsstepanovs thanks for the information!
So I will close this issue.
Regards!
